acf_1_1 <- ARMAacf(ar=0.6,ma=0.9,50)
acf_1_0 <- ARMAacf(ar=0.6,ma=0,50)
acf_0_1 <- ARMAacf(ar=0,ma=0.9,50)
plot(acf_1_1,type='l',ylab='value',xlab='lag',col='steelblue')
lines(acf_1_0,type='l',ylab='value',xlab='lag',col='orange')
lines(acf_0_1,type='l',ylab='value',xlab='lag',col='purple')
legend('topright',legend=c('ARMA(1,1)','ARMA(1,0)','ARMA(0,1)'),col=c('steelblue','orange','purple'),lty=1)

ARMA_1_1 <- arima.sim(list(order=c(1,0,1),ar=0.6,ma=0.9),n=100)
ARMA_1_0 <- arima.sim(list(order=c(1,0,0),ar=0.6),n=100)
ARMA_0_1 <- arima.sim(list(order=c(0,0,1),ma=0.9),n=100)

par(mfrow=c(1,3))
acf_s1 <- acf(ARMA_1_1,50,type='correlation',plot=F)
pacf_s1 <- pacf(ARMA_1_1,50,type='correlation',plot=F)
#lines(acf_1_1,col='red')
acf_s2 <- acf(ARMA_1_0,50,type='correlation',plot=F)
pacf_s2 <- pacf(ARMA_1_0,50,type='correlation',plot=F)
#lines(acf_1_0,col='red')
acf_s3 <- acf(ARMA_0_1,50,type='correlation',plot=F)
pacf_s3 <- pacf(ARMA_0_1,50,type='correlation',plot=F)
#lines(acf_0_1,col='red')
par(mfrow=c(1,3))
plot(acf_s1,type='l',col='steelblue')
lines(pacf_s1$acf,type='l',col='orange')
plot(acf_s2,type='l',col='steelblue')
lines(pacf_s2$acf,type='l',col='orange')
plot(acf_s3,type='l',col='steelblue')
lines(pacf_s3$acf,type='l',col='orange')
